/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'B_Negative' : null } |
  { 'AB_Positive' : null } |
  { 'O_Positive' : null } |
  { 'A_Negative' : null } |
  { 'B_Positive' : null } |
  { 'AB_Negative' : null } |
  { 'A_Positive' : null } |
  { 'O_Negative' : null };
export interface BloodRequest {
  'id' : bigint,
  'urgencyLevel' : UrgencyLevel,
  'city' : string,
  'createdAt' : bigint,
  'bloodGroup' : BloodGroup,
  'patientName' : string,
  'contactNumber' : string,
  'hospitalName' : string,
  'requesterId' : Principal,
  'quantityMl' : bigint,
}
export interface DonorProfile {
  'userId' : Principal,
  'lastDonationDate' : [] | [bigint],
  'availability' : boolean,
  'bloodGroup' : BloodGroup,
  'totalDonations' : bigint,
}
export interface DonorPublicInfo {
  'city' : string,
  'userId' : Principal,
  'name' : string,
  'lastDonationDate' : [] | [bigint],
  'availability' : boolean,
  'bloodGroup' : BloodGroup,
  'totalDonations' : bigint,
  'phone' : string,
}
export interface HospitalProfile {
  'isApproved' : boolean,
  'userId' : Principal,
  'address' : string,
  'licenseNumber' : string,
  'hospitalName' : string,
}
export interface PublicUserEntry {
  'city' : string,
  'name' : string,
  'role' : Role,
  'bloodGroup' : [] | [BloodGroup],
}
export type Role = { 'ngo' : null } |
  { 'hospital' : null } |
  { 'patient' : null } |
  { 'bloodBank' : null } |
  { 'admin' : null } |
  { 'donor' : null } |
  { 'volunteer' : null };
export type UrgencyLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface User {
  'id' : Principal,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : Role,
  'email' : string,
  'isVerified' : boolean,
  'bloodGroup' : [] | [BloodGroup],
  'phone' : string,
}
export interface UserProfile {
  'city' : string,
  'name' : string,
  'role' : Role,
  'email' : string,
  'bloodGroup' : [] | [BloodGroup],
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBloodRequest' : ActorMethod<[bigint], boolean>,
  'approveHospital' : ActorMethod<[Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeBloodRequest' : ActorMethod<[bigint], boolean>,
  'createBloodRequest' : ActorMethod<
    [string, BloodGroup, bigint, string, string, UrgencyLevel, string],
    bigint
  >,
  'getAllDonorsList' : ActorMethod<[], Array<DonorPublicInfo>>,
  'getAllHospitals' : ActorMethod<[], Array<HospitalProfile>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getBloodRequests' : ActorMethod<[], Array<BloodRequest>>,
  'getCallerDonorProfile' : ActorMethod<[], [] | [DonorProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonorProfile' : ActorMethod<[Principal], [] | [DonorProfile]>,
  'getPublicUserList' : ActorMethod<[], Array<PublicUserEntry>>,
  'getRoleCount' : ActorMethod<[Role], bigint>,
  'getTotalUsers' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, Role, string, [] | [BloodGroup]],
    Principal
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDonors' : ActorMethod<
    [[] | [BloodGroup], [] | [string], boolean],
    Array<DonorProfile>
  >,
  'searchDonorsPublic' : ActorMethod<
    [[] | [BloodGroup], [] | [string], [] | [string], boolean],
    Array<DonorPublicInfo>
  >,
  'updateDonorAvailability' : ActorMethod<[boolean], boolean>,
  'updateHospitalProfile' : ActorMethod<[string, string, string], boolean>,
  'updateUser' : ActorMethod<[User], undefined>,
  'upgrade' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];