/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodGroup = IDL.Variant({
  'B_Negative' : IDL.Null,
  'AB_Positive' : IDL.Null,
  'O_Positive' : IDL.Null,
  'A_Negative' : IDL.Null,
  'B_Positive' : IDL.Null,
  'AB_Negative' : IDL.Null,
  'A_Positive' : IDL.Null,
  'O_Negative' : IDL.Null,
});
export const UrgencyLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const DonorPublicInfo = IDL.Record({
  'city' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'lastDonationDate' : IDL.Opt(IDL.Int),
  'availability' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'totalDonations' : IDL.Nat,
  'phone' : IDL.Text,
});
export const HospitalProfile = IDL.Record({
  'isApproved' : IDL.Bool,
  'userId' : IDL.Principal,
  'address' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'hospitalName' : IDL.Text,
});
export const Role = IDL.Variant({
  'ngo' : IDL.Null,
  'hospital' : IDL.Null,
  'patient' : IDL.Null,
  'bloodBank' : IDL.Null,
  'admin' : IDL.Null,
  'donor' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
  'bloodGroup' : IDL.Opt(BloodGroup),
  'phone' : IDL.Text,
});
export const BloodRequest = IDL.Record({
  'id' : IDL.Nat,
  'urgencyLevel' : UrgencyLevel,
  'fulfilled' : IDL.Bool,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'bloodGroup' : BloodGroup,
  'patientName' : IDL.Text,
  'fulfilledBy' : IDL.Opt(IDL.Principal),
  'contactNumber' : IDL.Text,
  'hospitalName' : IDL.Text,
  'requesterId' : IDL.Principal,
  'quantityMl' : IDL.Nat,
  'thankYouMessage' : IDL.Opt(IDL.Text),
});
export const DonorProfile = IDL.Record({
  'userId' : IDL.Principal,
  'lastDonationDate' : IDL.Opt(IDL.Int),
  'availability' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'totalDonations' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'bloodGroup' : IDL.Opt(BloodGroup),
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'bloodRequestId' : IDL.Opt(IDL.Nat),
  'createdBy' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PublicUserEntry = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'bloodGroup' : IDL.Opt(BloodGroup),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveHospital' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBloodRequest' : IDL.Func(
      [
        IDL.Text,
        BloodGroup,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        UrgencyLevel,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAccount' : IDL.Func([], [IDL.Bool], []),
  'deleteBloodRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGlobalNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fulfillBloodRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'getAllDonorsList' : IDL.Func([], [IDL.Vec(DonorPublicInfo)], ['query']),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(HospitalProfile)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getBloodRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
  'getCallerDonorProfile' : IDL.Func([], [IDL.Opt(DonorProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonorProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DonorProfile)],
      ['query'],
    ),
  'getGlobalNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPublicUserList' : IDL.Func([], [IDL.Vec(PublicUserEntry)], ['query']),
  'getRoleCount' : IDL.Func([Role], [IDL.Nat], ['query']),
  'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(BloodGroup)],
      [IDL.Principal],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDonors' : IDL.Func(
      [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Vec(DonorProfile)],
      ['query'],
    ),
  'searchDonorsPublic' : IDL.Func(
      [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Vec(DonorPublicInfo)],
      ['query'],
    ),
  'updateDonorAvailability' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'updateHospitalProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateUser' : IDL.Func([User], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodGroup = IDL.Variant({
    'B_Negative' : IDL.Null,
    'AB_Positive' : IDL.Null,
    'O_Positive' : IDL.Null,
    'A_Negative' : IDL.Null,
    'B_Positive' : IDL.Null,
    'AB_Negative' : IDL.Null,
    'A_Positive' : IDL.Null,
    'O_Negative' : IDL.Null,
  });
  const UrgencyLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DonorPublicInfo = IDL.Record({
    'city' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'lastDonationDate' : IDL.Opt(IDL.Int),
    'availability' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'totalDonations' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const HospitalProfile = IDL.Record({
    'isApproved' : IDL.Bool,
    'userId' : IDL.Principal,
    'address' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'hospitalName' : IDL.Text,
  });
  const Role = IDL.Variant({
    'ngo' : IDL.Null,
    'hospital' : IDL.Null,
    'patient' : IDL.Null,
    'bloodBank' : IDL.Null,
    'admin' : IDL.Null,
    'donor' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
    'bloodGroup' : IDL.Opt(BloodGroup),
    'phone' : IDL.Text,
  });
  const BloodRequest = IDL.Record({
    'id' : IDL.Nat,
    'urgencyLevel' : UrgencyLevel,
    'fulfilled' : IDL.Bool,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'bloodGroup' : BloodGroup,
    'patientName' : IDL.Text,
    'fulfilledBy' : IDL.Opt(IDL.Principal),
    'contactNumber' : IDL.Text,
    'hospitalName' : IDL.Text,
    'requesterId' : IDL.Principal,
    'quantityMl' : IDL.Nat,
    'thankYouMessage' : IDL.Opt(IDL.Text),
  });
  const DonorProfile = IDL.Record({
    'userId' : IDL.Principal,
    'lastDonationDate' : IDL.Opt(IDL.Int),
    'availability' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'totalDonations' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'bloodGroup' : IDL.Opt(BloodGroup),
    'phone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'bloodRequestId' : IDL.Opt(IDL.Nat),
    'createdBy' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PublicUserEntry = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'bloodGroup' : IDL.Opt(BloodGroup),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveHospital' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBloodRequest' : IDL.Func(
        [
          IDL.Text,
          BloodGroup,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          UrgencyLevel,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAccount' : IDL.Func([], [IDL.Bool], []),
    'deleteBloodRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGlobalNotification' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fulfillBloodRequest' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'getAllDonorsList' : IDL.Func([], [IDL.Vec(DonorPublicInfo)], ['query']),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(HospitalProfile)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getBloodRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
    'getCallerDonorProfile' : IDL.Func([], [IDL.Opt(DonorProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonorProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DonorProfile)],
        ['query'],
      ),
    'getGlobalNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPublicUserList' : IDL.Func([], [IDL.Vec(PublicUserEntry)], ['query']),
    'getRoleCount' : IDL.Func([Role], [IDL.Nat], ['query']),
    'getTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(BloodGroup)],
        [IDL.Principal],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDonors' : IDL.Func(
        [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Vec(DonorProfile)],
        ['query'],
      ),
    'searchDonorsPublic' : IDL.Func(
        [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Vec(DonorPublicInfo)],
        ['query'],
      ),
    'updateDonorAvailability' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'updateHospitalProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateUser' : IDL.Func([User], [], []),
  });
};

export const init = ({ IDL }) => { return []; };