/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BloodRequest {
    id: bigint;
    urgencyLevel: UrgencyLevel;
    city: string;
    createdAt: bigint;
    bloodGroup: BloodGroup;
    patientName: string;
    contactNumber: string;
    hospitalName: string;
    requesterId: Principal;
    quantityMl: bigint;
}
export interface User {
    id: Principal;
    city: string;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    isVerified: boolean;
    bloodGroup?: BloodGroup;
    phone: string;
}
export interface DonorProfile {
    userId: Principal;
    lastDonationDate?: bigint;
    availability: boolean;
    bloodGroup: BloodGroup;
    totalDonations: bigint;
}
export interface HospitalProfile {
    isApproved: boolean;
    userId: Principal;
    address: string;
    licenseNumber: string;
    hospitalName: string;
}
export interface UserProfile {
    city: string;
    name: string;
    role: Role;
    email: string;
    bloodGroup?: BloodGroup;
    phone: string;
}
export enum BloodGroup {
    B_Negative = "B_Negative",
    AB_Positive = "AB_Positive",
    O_Positive = "O_Positive",
    A_Negative = "A_Negative",
    B_Positive = "B_Positive",
    AB_Negative = "AB_Negative",
    A_Positive = "A_Positive",
    O_Negative = "O_Negative"
}
export enum Role {
    ngo = "ngo",
    hospital = "hospital",
    patient = "patient",
    bloodBank = "bloodBank",
    admin = "admin",
    donor = "donor",
    volunteer = "volunteer"
}
export enum UrgencyLevel {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptBloodRequest(requestId: bigint): Promise<boolean>;
    approveHospital(hospitalId: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeBloodRequest(requestId: bigint): Promise<boolean>;
    createBloodRequest(patientName: string, bloodGroup: BloodGroup, quantityMl: bigint, hospitalName: string, city: string, urgency: UrgencyLevel, contact: string): Promise<bigint>;
    getAllHospitals(): Promise<Array<HospitalProfile>>;
    getAllUsers(): Promise<Array<User>>;
    getBloodRequests(): Promise<Array<BloodRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonorProfile(userId: Principal): Promise<DonorProfile | null>;
    getUser(userId: Principal): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initSystem(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(name: string, email: string, phone: string, role: Role, city: string, bloodGroup: BloodGroup | null): Promise<Principal>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDonors(bloodGroup: BloodGroup | null, city: string | null, availableOnly: boolean): Promise<Array<DonorProfile>>;
    updateDonorAvailability(available: boolean): Promise<boolean>;
    updateUser(user: User): Promise<void>;
}
import type { BloodGroup as _BloodGroup, BloodRequest as _BloodRequest, DonorProfile as _DonorProfile, Role as _Role, UrgencyLevel as _UrgencyLevel, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptBloodRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptBloodRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptBloodRequest(arg0);
            return result;
        }
    }
    async approveHospital(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveHospital(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeBloodRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBloodRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBloodRequest(arg0);
            return result;
        }
    }
    async createBloodRequest(arg0: string, arg1: BloodGroup, arg2: bigint, arg3: string, arg4: string, arg5: UrgencyLevel, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBloodRequest(arg0, to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_UrgencyLevel_n5(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBloodRequest(arg0, to_candid_BloodGroup_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_UrgencyLevel_n5(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async getAllHospitals(): Promise<Array<HospitalProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHospitals();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBloodRequests(): Promise<Array<BloodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorProfile(arg0: Principal): Promise<DonorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSystem(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSystem();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSystem();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string, arg5: BloodGroup | null): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_Role_n29(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_Role_n29(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchDonors(arg0: BloodGroup | null, arg1: string | null, arg2: boolean): Promise<Array<DonorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonors(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonors(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDonorAvailability(arg0: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonorAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonorAvailability(arg0);
            return result;
        }
    }
    async updateUser(arg0: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_User_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_User_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BloodGroup_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BloodRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequest): BloodRequest {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DonorProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorProfile): DonorProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UrgencyLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UrgencyLevel): UrgencyLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_User_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BloodGroup]): BloodGroup | null {
    return value.length === 0 ? null : from_candid_BloodGroup_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DonorProfile]): DonorProfile | null {
    return value.length === 0 ? null : from_candid_DonorProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    urgencyLevel: _UrgencyLevel;
    city: string;
    createdAt: bigint;
    bloodGroup: _BloodGroup;
    patientName: string;
    contactNumber: string;
    hospitalName: string;
    requesterId: Principal;
    quantityMl: bigint;
}): {
    id: bigint;
    urgencyLevel: UrgencyLevel;
    city: string;
    createdAt: bigint;
    bloodGroup: BloodGroup;
    patientName: string;
    contactNumber: string;
    hospitalName: string;
    requesterId: Principal;
    quantityMl: bigint;
} {
    return {
        id: value.id,
        urgencyLevel: from_candid_UrgencyLevel_n18(_uploadFile, _downloadFile, value.urgencyLevel),
        city: value.city,
        createdAt: value.createdAt,
        bloodGroup: from_candid_BloodGroup_n13(_uploadFile, _downloadFile, value.bloodGroup),
        patientName: value.patientName,
        contactNumber: value.contactNumber,
        hospitalName: value.hospitalName,
        requesterId: value.requesterId,
        quantityMl: value.quantityMl
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    role: _Role;
    email: string;
    bloodGroup: [] | [_BloodGroup];
    phone: string;
}): {
    city: string;
    name: string;
    role: Role;
    email: string;
    bloodGroup?: BloodGroup;
    phone: string;
} {
    return {
        city: value.city,
        name: value.name,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        bloodGroup: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.bloodGroup)),
        phone: value.phone
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    lastDonationDate: [] | [bigint];
    availability: boolean;
    bloodGroup: _BloodGroup;
    totalDonations: bigint;
}): {
    userId: Principal;
    lastDonationDate?: bigint;
    availability: boolean;
    bloodGroup: BloodGroup;
    totalDonations: bigint;
} {
    return {
        userId: value.userId,
        lastDonationDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastDonationDate)),
        availability: value.availability,
        bloodGroup: from_candid_BloodGroup_n13(_uploadFile, _downloadFile, value.bloodGroup),
        totalDonations: value.totalDonations
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    city: string;
    name: string;
    createdAt: bigint;
    role: _Role;
    email: string;
    isVerified: boolean;
    bloodGroup: [] | [_BloodGroup];
    phone: string;
}): {
    id: Principal;
    city: string;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    isVerified: boolean;
    bloodGroup?: BloodGroup;
    phone: string;
} {
    return {
        id: value.id,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n10(_uploadFile, _downloadFile, value.role),
        email: value.email,
        isVerified: value.isVerified,
        bloodGroup: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.bloodGroup)),
        phone: value.phone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    hospital: null;
} | {
    patient: null;
} | {
    bloodBank: null;
} | {
    admin: null;
} | {
    donor: null;
} | {
    volunteer: null;
}): Role {
    return "ngo" in value ? Role.ngo : "hospital" in value ? Role.hospital : "patient" in value ? Role.patient : "bloodBank" in value ? Role.bloodBank : "admin" in value ? Role.admin : "donor" in value ? Role.donor : "volunteer" in value ? Role.volunteer : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    B_Negative: null;
} | {
    AB_Positive: null;
} | {
    O_Positive: null;
} | {
    A_Negative: null;
} | {
    B_Positive: null;
} | {
    AB_Negative: null;
} | {
    A_Positive: null;
} | {
    O_Negative: null;
}): BloodGroup {
    return "B_Negative" in value ? BloodGroup.B_Negative : "AB_Positive" in value ? BloodGroup.AB_Positive : "O_Positive" in value ? BloodGroup.O_Positive : "A_Negative" in value ? BloodGroup.A_Negative : "B_Positive" in value ? BloodGroup.B_Positive : "AB_Negative" in value ? BloodGroup.AB_Negative : "A_Positive" in value ? BloodGroup.A_Positive : "O_Negative" in value ? BloodGroup.O_Negative : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): UrgencyLevel {
    return "low" in value ? UrgencyLevel.low : "high" in value ? UrgencyLevel.high : "critical" in value ? UrgencyLevel.critical : "medium" in value ? UrgencyLevel.medium : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodRequest>): Array<BloodRequest> {
    return value.map((x)=>from_candid_BloodRequest_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorProfile>): Array<DonorProfile> {
    return value.map((x)=>from_candid_DonorProfile_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UrgencyLevel_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): _UrgencyLevel {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_User_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): _User {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup | null): [] | [_BloodGroup] {
    return value === null ? candid_none() : candid_some(to_candid_BloodGroup_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    role: Role;
    email: string;
    bloodGroup?: BloodGroup;
    phone: string;
}): {
    city: string;
    name: string;
    role: _Role;
    email: string;
    bloodGroup: [] | [_BloodGroup];
    phone: string;
} {
    return {
        city: value.city,
        name: value.name,
        role: to_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        bloodGroup: value.bloodGroup ? candid_some(to_candid_BloodGroup_n3(_uploadFile, _downloadFile, value.bloodGroup)) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    city: string;
    name: string;
    createdAt: bigint;
    role: Role;
    email: string;
    isVerified: boolean;
    bloodGroup?: BloodGroup;
    phone: string;
}): {
    id: Principal;
    city: string;
    name: string;
    createdAt: bigint;
    role: _Role;
    email: string;
    isVerified: boolean;
    bloodGroup: [] | [_BloodGroup];
    phone: string;
} {
    return {
        id: value.id,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        isVerified: value.isVerified,
        bloodGroup: value.bloodGroup ? candid_some(to_candid_BloodGroup_n3(_uploadFile, _downloadFile, value.bloodGroup)) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    ngo: null;
} | {
    hospital: null;
} | {
    patient: null;
} | {
    bloodBank: null;
} | {
    admin: null;
} | {
    donor: null;
} | {
    volunteer: null;
} {
    return value == Role.ngo ? {
        ngo: null
    } : value == Role.hospital ? {
        hospital: null
    } : value == Role.patient ? {
        patient: null
    } : value == Role.bloodBank ? {
        bloodBank: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.donor ? {
        donor: null
    } : value == Role.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    B_Negative: null;
} | {
    AB_Positive: null;
} | {
    O_Positive: null;
} | {
    A_Negative: null;
} | {
    B_Positive: null;
} | {
    AB_Negative: null;
} | {
    A_Positive: null;
} | {
    O_Negative: null;
} {
    return value == BloodGroup.B_Negative ? {
        B_Negative: null
    } : value == BloodGroup.AB_Positive ? {
        AB_Positive: null
    } : value == BloodGroup.O_Positive ? {
        O_Positive: null
    } : value == BloodGroup.A_Negative ? {
        A_Negative: null
    } : value == BloodGroup.B_Positive ? {
        B_Positive: null
    } : value == BloodGroup.AB_Negative ? {
        AB_Negative: null
    } : value == BloodGroup.A_Positive ? {
        A_Positive: null
    } : value == BloodGroup.O_Negative ? {
        O_Negative: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == UrgencyLevel.low ? {
        low: null
    } : value == UrgencyLevel.high ? {
        high: null
    } : value == UrgencyLevel.critical ? {
        critical: null
    } : value == UrgencyLevel.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
